name: flutter_listings
description: A new Listings Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  page_view_indicators: ^1.3.1
  shared_preferences: ^0.5.8
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  image_picker: ^0.6.5
  firebase_storage: ^3.1.5
  progress_dialog: ^1.2.2
  provider: ^4.0.1
  url_launcher: ^5.5.0
  intl: ^0.16.1
  cached_network_image: ^2.1.0+1
  uuid: ^2.0.4
  video_thumbnail: ^0.2.1
  path_provider: ^1.6.7
  photo_view: ^0.10.0
  video_player: ^0.10.9+1
  flutter_facebook_login: ^3.0.0
  http: ^0.12.1
  location: ^3.0.0
  latlong: ^0.6.1
  smooth_page_indicator: ^0.2.0
  firebase_messaging: ^6.0.16
  intl_phone_number_input: ^0.4.6+2
  pin_code_fields: ^5.0.0
  in_app_purchase: ^0.3.4+1
  audio_recorder: ^1.0.2
  audioplayers: ^0.15.1
  permission_handler: ^5.0.1+1
  flutter_rating_bar: ^3.0.1+1
  google_maps_flutter: ^0.5.28+1
  flutter_google_places: ^0.2.6
  google_maps_webservice: ^0.0.17
  webview_flutter_plus: ^0.1.1+10

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/images/real_estate.png'

flutter:

  uses-material-design: true
  assets:
    - assets/images/

